### ISSUE TITLE
Allow creators to input people's timezones to check availability

### ISSUE THREAD

**Issue by anandbaburajan** [anandbaburajan/samay#5]
Before choosing candidates, the poll creator could be given an option to enter timezones of all participants. Then while choosing candidates, the app could help the creator know (maybe in a tooltip) what time the hovered candidate would be in others' timezones.

**Comment by AnandBaburajan** [comment]
@manishprivet do you have any doubts or do you need something to continue working on this?

**Comment by manishprivet** [comment]
Hi @AnandBaburajan, I was in the process of recovering from COVID-19 for the past month. Is it okay if I get back on it in a few days?

**Comment by AnandBaburajan** [comment]
> Hi @AnandBaburajan, I was in the process of recovering from COVID-19 for the past month. Is it okay if I get back on it in a few days?

Oh. Yep!

**Comment by aysp-99** [comment]
Hi. Sorry for being inactive for quite a while. I'd like to work on this feature. I've got a doubt, Would this feature be only used for "private polls"?

**Comment by AnandBaburajan** [comment]
Hello @aysp-99! Welcome back! We've been inactive for a while but I plan to wrap up the MVP and launch this soon. This feature can be in all types of polls, right? Also, since you're interested in contributing here, what do you think about looking into https://github.com/RocketMeet/RocketMeet-client/issues/103? This is more interesting and important for us right now. Let me know what you think! :D Thank you a lot for showing interest! Please feel free to check this out https://calendly.com/anandbaburajan/30min and I'll be happy to help!

**Comment by aysp-99** [comment]
> Hello @aysp-99! Welcome back! We've been inactive for a while but I plan to wrap up the MVP and launch this soon. This feature can be in all types of polls, right?

If I have understood correctly, the poll creator can only choose candidates for private and protected mode so the time zones would only be showed for those candidates.
 >Also, since you're interested in contributing here, what do you think about looking into #103? This is more interesting and important for us right now. Let me know what you think! :D

Sure, I will look into it.
>Thank you a lot for showing interest! Please feel free to check this out https://calendly.com/anandbaburajan/30min and I'll be happy to help!

Thank you, really appreciate it.

**Comment by AnandBaburajan** [comment]
> If I have understood correctly, the poll creator can only choose candidates for private and protected mode so the time zones would only be showed for those candidates.

Oh, yep! You're right!

> Sure, I will look into it.

:D

> Thank you, really appreciate it.

:D

**Comment by AnandBaburajan** [comment]
We're not sure if there are users who need this feature, hence marking this issue as 'discussion' as of now.

If you would like this feature, please let us know!
